<?php

function title_case_menu() {
  $items['title_case'] = array(
    'title' => 'Title Caser',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['title_case_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function title_case_form() {
  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter a phrase to be converted to title case.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Title Case It',
  );
  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $phrase = $form_state['values']['phrase'];
  $lower_case_phrase = strtolower($phrase);
  $title_case_phrase = ucwords($lower_case_phrase);
  $_SESSION['title_case_output'] = $title_case_phrase;

  $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  $answer = $_SESSION['title_case_output'];
  return $answer;
}
